#Do not change this manually, this is to keep track of config changes.
config-version: 3

#If this is set to false, it will convert current ender chests to be used by this plugin;
#Whether this is set to true or false, does NOT affect the enderchest contents that is saved by default minecraft.
convert-current-ender-chest: true

#If this is set to 0, players will need a permission to be able to open an enderchest
default-rows: 3

#These are messages that will be sent to players.
command-permission-self: '&4You do not have permission to use this command.'
command-permission-others: '&4You do not have permission to view the enderchest of others.'
no-enderchest-found: '&4That player does not have an enderchest.'
no-rows: '&4You do not have an enderchest.'

#These are the inventory names that players will see when they open their inventory
#You can set a different name for each size eg. Level 1, Level 2
#<player> is replaced with the player's name
enderchest-names:
  1-rows: "&7<player>'s Enderchest"
  2-rows: "&7<player>'s Enderchest"
  3-rows: "&7<player>'s Enderchest"
  4-rows: "&7<player>'s Enderchest"
  5-rows: "&7<player>'s Enderchest"
  6-rows: "&7<player>'s Enderchest"

blacklisted-message: '&4You cannot put that item into an ender chest.'
blacklisted-items:
  - 'COMMAND_BLOCK'
